package com.game.constants;

public class Constants {

    public static String[] bootstrapQueries = {
            "PLAYER=0,COMMAND=REGISTER_PLAYER NAME=ADAM",
            "PLAYER=0,COMMAND=REGISTER_PLAYER NAME=EVE",
            "PLAYER=1,COMMAND=CREATE_GAME PLAYER1=1 PLAYER2=2",
            "PLAYER=1,COMMAND=CREATE_SHIP GAME=1 ALIGNMENT=HORIZONTAL SHIP=CARRIER LOCATION=A1",
            "PLAYER=1,COMMAND=CREATE_SHIP GAME=1 ALIGNMENT=VERTICAL SHIP=BATTLESHIP LOCATION=B2",
            "PLAYER=1,COMMAND=CREATE_SHIP GAME=1 ALIGNMENT=HORIZONTAL SHIP=CRUISER LOCATION=D5",
            "PLAYER=1,COMMAND=CREATE_SHIP GAME=1 ALIGNMENT=VERTICAL SHIP=SUBMARINE LOCATION=E6",
            "PLAYER=1,COMMAND=CREATE_SHIP GAME=1 ALIGNMENT=HORIZONTAL SHIP=DESTROYER LOCATION=A7",
            "PLAYER=2,COMMAND=CREATE_SHIP GAME=1 ALIGNMENT=VERTICAL SHIP=CARRIER LOCATION=A4",
            "PLAYER=2,COMMAND=CREATE_SHIP GAME=1 ALIGNMENT=HORIZONTAL SHIP=BATTLESHIP LOCATION=B3",
            "PLAYER=2,COMMAND=CREATE_SHIP GAME=1 ALIGNMENT=VERTICAL SHIP=CRUISER LOCATION=C4",
            "PLAYER=2,COMMAND=CREATE_SHIP GAME=1 ALIGNMENT=HORIZONTAL SHIP=SUBMARINE LOCATION=D5",
            "PLAYER=2,COMMAND=CREATE_SHIP GAME=1 ALIGNMENT=VERTICAL SHIP=DESTROYER LOCATION=F7"
    };


}
